### ISSUE TITLE
Missing :

### ISSUE THREAD

**Issue by hinogi** [Youhan/VSCode-Snippets-Shopify-Content-Schema#1]
after info the : is missing leading to invalid json.

https://github.com/Youhan/VSCode-Snippets-Shopify-Content-Schema/blob/50324b088d505d354c7011e4bf44c2fe5e83897c/snippets/liquid.json#L211

**Comment by Youhan** [comment]
Oh! Somehow I missed this. Sorry about that. It is fixed in v 1.3.1 now.
